services:
  backend:
    build: ./backend
    container_name: kinetix-app
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: ${MONGO_URI}
      MEILI_HOST: ${MEILI_HOST}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      NODE_ENV: ${NODE_ENV}
      AZURE_LANGUAGE_ENDPOINT: ${AZURE_LANGUAGE_ENDPOINT}
      AZURE_LANGUAGE_KEY: ${AZURE_LANGUAGE_KEY}
      AZURE_VISION_ENDPOINT: ${AZURE_VISION_ENDPOINT}
      AZURE_VISION_KEY: ${AZURE_VISION_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - meilisearch
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: kinetix-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_ENV: "development"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  meili_data:
